local source = {}

local symbol_table = {
    {word = "\\alpha", label = "\\alpha α", insertText = "α", filter_text = "\\alpha"},
    {word = "\\beta", label = "\\beta β", insertText = "β", filter_text = "\\beta"},
    {word = "\\varbeta", label = "\\varbeta ϐ", insertText = "ϐ", filter_text = "\\varbeta"},
    {word = "\\gamma", label = "\\gamma γ", insertText = "γ", filter_text = "\\gamma"},
    {word = "\\delta", label = "\\delta δ", insertText = "δ", filter_text = "\\delta"},
    {word = "\\epsilon", label = "\\epsilon ϵ", insertText = "ϵ", filter_text = "\\epsilon"},
    {word = "\\backepsilon", label = "\\backepsilon ϶", insertText = "϶", filter_text = "\\backepsilon"},
    {word = "\\varepsilon", label = "\\varepsilon ε", insertText = "ε", filter_text = "\\varepsilon"},
    {word = "\\zeta", label = "\\zeta ζ", insertText = "ζ", filter_text = "\\zeta"},
    {word = "\\eta", label = "\\eta η", insertText = "η", filter_text = "\\eta"},
    {word = "\\theta", label = "\\theta θ", insertText = "θ", filter_text = "\\theta"},
    {word = "\\vartheta", label = "\\vartheta ϑ", insertText = "ϑ", filter_text = "\\vartheta"},
    {word = "\\iota", label = "\\iota ι", insertText = "ι", filter_text = "\\iota"},
    {word = "\\kappa", label = "\\kappa κ", insertText = "κ", filter_text = "\\kappa"},
    {word = "\\varkappa", label = "\\varkappa ϰ", insertText = "ϰ", filter_text = "\\varkappa"},
    {word = "\\lambda", label = "\\lambda λ", insertText = "λ", filter_text = "\\lambda"},
    {word = "\\mu", label = "\\mu μ", insertText = "μ", filter_text = "\\mu"},
    {word = "\\nu", label = "\\nu ν", insertText = "ν", filter_text = "\\nu"},
    {word = "\\xi", label = "\\xi ξ", insertText = "ξ", filter_text = "\\xi"},
    {word = "\\pi", label = "\\pi π", insertText = "π", filter_text = "\\pi"},
    {word = "\\varpi", label = "\\varpi ϖ", insertText = "ϖ", filter_text = "\\varpi"},
    {word = "\\rho", label = "\\rho ρ", insertText = "ρ", filter_text = "\\rho"},
    {word = "\\varrho", label = "\\varrho ϱ", insertText = "ϱ", filter_text = "\\varrho"},
    {word = "\\varsigma", label = "\\varsigma ς", insertText = "ς", filter_text = "\\varsigma"},
    {word = "\\sigma", label = "\\sigma σ", insertText = "σ", filter_text = "\\sigma"},
    {word = "\\tau", label = "\\tau τ", insertText = "τ", filter_text = "\\tau"},
    {word = "\\upsilon", label = "\\upsilon υ", insertText = "υ", filter_text = "\\upsilon"},
    {word = "\\phi", label = "\\phi ϕ", insertText = "ϕ", filter_text = "\\phi"},
    {word = "\\varphi", label = "\\varphi φ", insertText = "φ", filter_text = "\\varphi"},
    {word = "\\chi", label = "\\chi χ", insertText = "χ", filter_text = "\\chi"},
    {word = "\\psi", label = "\\psi ψ", insertText = "ψ", filter_text = "\\psi"},
    {word = "\\omega", label = "\\omega ω", insertText = "ω", filter_text = "\\omega"},
    {word = "\\qoppa", label = "\\qoppa ϙ", insertText = "ϙ", filter_text = "\\qoppa"},
    {word = "\\stigma", label = "\\stigma ϛ", insertText = "ϛ", filter_text = "\\stigma"},
    {word = "\\digamma", label = "\\digamma ϝ", insertText = "ϝ", filter_text = "\\digamma"},
    {word = "\\koppa", label = "\\koppa ϟ", insertText = "ϟ", filter_text = "\\koppa"},
    {word = "\\sampi", label = "\\sampi ϡ", insertText = "ϡ", filter_text = "\\sampi"},

    {word = "\\Gamma", label = "\\Gamma Γ", insertText = "Γ", filter_text = "\\Gamma"},
    {word = "\\Delta", label = "\\Delta Δ", insertText = "Δ", filter_text = "\\Delta"},
    {word = "\\Theta", label = "\\Theta Θ", insertText = "Θ", filter_text = "\\Theta"},
    {word = "\\Lambda", label = "\\Lambda Λ", insertText = "Λ", filter_text = "\\Lambda"},
    {word = "\\Xi", label = "\\Xi Ξ", insertText = "Ξ", filter_text = "\\Xi"},
    {word = "\\Pi", label = "\\Pi Π", insertText = "Π", filter_text = "\\Pi"},
    {word = "\\Sigma", label = "\\Sigma Σ", insertText = "Σ", filter_text = "\\Sigma"},
    {word = "\\Phi", label = "\\Phi Φ", insertText = "Φ", filter_text = "\\Phi"},
    {word = "\\Psi", label = "\\Psi Ψ", insertText = "Ψ", filter_text = "\\Psi"},
    {word = "\\Omega", label = "\\Omega Ω", insertText = "Ω", filter_text = "\\Omega"},
    {word = "\\Qoppa", label = "\\Qoppa Ϙ", insertText = "Ϙ", filter_text = "\\Qoppa"},
    {word = "\\Stigma", label = "\\Stigma Ϛ", insertText = "Ϛ", filter_text = "\\Stigma"},
    {word = "\\Digamma", label = "\\Digamma Ϝ", insertText = "Ϝ", filter_text = "\\Digamma"},
    {word = "\\Koppa", label = "\\Koppa Ϟ", insertText = "Ϟ", filter_text = "\\Koppa"},
    {word = "\\Sampi", label = "\\Sampi Ϡ", insertText = "Ϡ", filter_text = "\\Sampi"},

    {word = "\\forall", label = "\\forall ∀", insertText = "∀", filter_text = "\\forall"},
    {word = "\\exists", label = "\\exists ∃", insertText = "∃", filter_text = "\\exists"},
    {word = "\\nexists", label = "\\nexists ∄", insertText = "∄", filter_text = "\\nexists"},
    {word = "\\in", label = "\\in ∈", insertText = "∈", filter_text = "\\in"},
    {word = "\\notin", label = "\\notin ∉", insertText = "∉", filter_text = "\\notin"},
    {word = "\\ni", label = "\\ni ∋", insertText = "∋", filter_text = "\\ni"},
    {word = "\\nni", label = "\\nni ∌", insertText = "∌", filter_text = "\\nni"},
    {word = "\\therefore", label = "\\therefore ∴", insertText = "∴", filter_text = "\\therefore"},
    {word = "\\because", label = "\\because ∵", insertText = "∵", filter_text = "\\because"},

    {word = "\\Finv", label = "\\Finv Ⅎ", insertText = "Ⅎ", filter_text = "\\Finv"},
    {word = "\\varnothing", label = "\\varnothing ∅", insertText = "∅", filter_text = "\\varnothing"},
    {word = "\\infty", label = "\\infty ∞", insertText = "∞", filter_text = "\\infty"},

    {word = "\\ldots", label = "\\ldots …", insertText = "…", filter_text = "\\ldots"},
    {word = "\\cdots", label = "\\cdots ⋯", insertText = "⋯", filter_text = "\\cdots"},
    {word = "\\vdots", label = "\\vdots ⋮", insertText = "⋮", filter_text = "\\vdots"},

    {word = "\\neg", label = "\\neg ¬", insertText = "¬", filter_text = "\\neg"},
    {word = "\\pm", label = "\\pm ±", insertText = "±", filter_text = "\\pm"},
    {word = "\\times", label = "\\times ×", insertText = "×", filter_text = "\\times"},
    {word = "\\partial", label = "\\partial ∂", insertText = "∂", filter_text = "\\partial"},
    {word = "\\nabla", label = "\\nabla ∇", insertText = "∇", filter_text = "\\nabla"},
    {word = "\\prod", label = "\\prod ∏", insertText = "∏", filter_text = "\\prod"},
    {word = "\\sum", label = "\\sum ∑", insertText = "∑", filter_text = "\\sum"},
    {word = "\\minus", label = "\\minus −", insertText = "−", filter_text = "\\minus"},
    {word = "\\mp", label = "\\mp ∓", insertText = "∓", filter_text = "\\mp"},
    {word = "\\wedge", label = "\\wedge ∧", insertText = "∧", filter_text = "\\wedge"},
    {word = "\\vee", label = "\\vee ∨", insertText = "∨", filter_text = "\\vee"},
    {word = "\\cap", label = "\\cap ∩", insertText = "∩", filter_text = "\\cap"},
    {word = "\\cup", label = "\\cup ∪", insertText = "∪", filter_text = "\\cup"},
    {word = "\\int", label = "\\int ∫", insertText = "∫", filter_text = "\\int"},
    {word = "\\iint", label = "\\iint ∬", insertText = "∬", filter_text = "\\iint"},
    {word = "\\iiint", label = "\\iiint ∭", insertText = "∭", filter_text = "\\iiint"},
    {word = "\\oint", label = "\\oint ∮", insertText = "∮", filter_text = "\\oint"},
    {word = "\\oiint", label = "\\oiint ∯", insertText = "∯", filter_text = "\\oiint"},
    {word = "\\oiiint", label = "\\oiiint ∰", insertText = "∰", filter_text = "\\oiiint"},
    {word = "\\sim", label = "\\sim ∼", insertText = "∼", filter_text = "\\sim"},
    {word = "\\nsim", label = "\\nsim ≁", insertText = "≁", filter_text = "\\nsim"},
    {word = "\\simeq", label = "\\simeq ≃", insertText = "≃", filter_text = "\\simeq"},
    {word = "\\nsimeq", label = "\\nsimeq ≄", insertText = "≄", filter_text = "\\nsimeq"},
    {word = "\\cong", label = "\\cong ≅", insertText = "≅", filter_text = "\\cong"},
    {word = "\\ncong", label = "\\ncong ≇", insertText = "≇", filter_text = "\\ncong"},
    {word = "\\approx", label = "\\approx ≈", insertText = "≈", filter_text = "\\approx"},
    {word = "\\napprox", label = "\\napprox ≉", insertText = "≉", filter_text = "\\napprox"},
    {word = "\\approxeq", label = "\\approxeq ≊", insertText = "≊", filter_text = "\\approxeq"},
    {word = "\\approxident", label = "\\approxident ≋", insertText = "≋", filter_text = "\\approxident"},
    {word = "\\neq", label = "\\neq ≠", insertText = "≠", filter_text = "\\neq"},
    {word = "\\ne", label = "\\ne ≠", insertText = "≠", filter_text = "\\ne"},
    {word = "\\equiv", label = "\\equiv ≡", insertText = "≡", filter_text = "\\equiv"},
    {word = "\\nequiv", label = "\\nequiv ≢", insertText = "≢", filter_text = "\\nequiv"},
    {word = "\\leq", label = "\\leq ≤", insertText = "≤", filter_text = "\\leq"},
    {word = "\\geq", label = "\\geq ≥", insertText = "≥", filter_text = "\\geq"},
    {word = "\\leqq", label = "\\leqq ≦", insertText = "≦", filter_text = "\\leqq"},
    {word = "\\geqq", label = "\\geqq ≧", insertText = "≧", filter_text = "\\geqq"},
    {word = "\\ll", label = "\\ll ≪", insertText = "≪", filter_text = "\\ll"},
    {word = "\\gg", label = "\\gg ≫", insertText = "≫", filter_text = "\\gg"},
    {word = "\\oplus", label = "\\oplus ⊕", insertText = "⊕", filter_text = "\\oplus"},
    {word = "\\otimes", label = "\\otimes ⊗", insertText = "⊗", filter_text = "\\otimes"},
    {word = "\\cdot", label = "\\cdot ⋅", insertText = "⋅", filter_text = "\\cdot"},
    {word = "\\star", label = "\\star ⋆", insertText = "⋆", filter_text = "\\star"},
    {word = "\\ast", label = "\\ast ∗", insertText = "∗", filter_text = "\\ast"},
    {word = "\\circ", label = "\\circ ∘", insertText = "∘", filter_text = "\\circ"},
    {word = "\\propto", label = "\\propto ∝", insertText = "∝", filter_text = "\\propto"},

    {word = "\\dagger", label = "\\dagger †", insertText = "†", filter_text = "\\dagger"},
    {word = "\\ddagger", label = "\\ddagger ‡", insertText = "‡", filter_text = "\\ddagger"},
    {word = "\\bullet", label = "\\bullet •", insertText = "•", filter_text = "\\bullet"},

    {word = "\\prime", label = "\\prime ′", insertText = "′", filter_text = "\\prime"},
    {word = "\\dprime", label = "\\dprime ″", insertText = "″", filter_text = "\\dprime"},
    {word = "\\trprime", label = "\\trprime ‴", insertText = "‴", filter_text = "\\trprime"},
    {word = "\\qprime", label = "\\qprime ⁗", insertText = "⁗", filter_text = "\\qprime"},

    {word = "\\leftarrow", label = "\\leftarrow ←", insertText = "←", filter_text = "\\leftarrow"},
    {word = "\\uparrow", label = "\\uparrow ↑", insertText = "↑", filter_text = "\\uparrow"},
    {word = "\\rightarrow", label = "\\rightarrow →", insertText = "→", filter_text = "\\rightarrow"},
    {word = "\\downarrow", label = "\\downarrow ↓", insertText = "↓", filter_text = "\\downarrow"},
    {word = "\\leftrightarrow", label = "\\leftrightarrow ↔", insertText = "↔", filter_text = "\\leftrightarrow"},
    {word = "\\mapsto", label = "\\mapsto ↦", insertText = "↦", filter_text = "\\mapsto"},
    {word = "\\MapsDown", label = "\\MapsDown ↧", insertText = "↧", filter_text = "\\MapsDown"},
    {word = "\\mapsdown", label = "\\mapsdown ↧", insertText = "↧", filter_text = "\\mapsdown"},
    {word = "\\lightning", label = "\\lightning ↯", insertText = "↯", filter_text = "\\lightning"},
    {word = "\\Longleftarrow", label = "\\Longleftarrow ⟸", insertText = "⟸", filter_text = "\\Longleftarrow"},
    {word = "\\Longrightarrow", label = "\\Longrightarrow ⟹", insertText = "⟹", filter_text = "\\Longrightarrow"}
}

function source:is_available()
    -- In TeX we want to insert the literal command, not the character.
    return vim.bo.filetype ~= "tex"
end

function source:get_trigger_characters()
    return {[[\]]}
end

function source:complete(_, callback)
    return callback(symbol_table)
end

return source
